### ISSUE TITLE
18.04: "Pop!_OS 20.04" should probably say it's an LTS

### ISSUE THREAD

**Issue by leviport** [pop-os/upgrade#110]
Since the 18.04 version contains LTS, some users might not know if 20.04 is also an LTS, possibly discouraging upgrading. Where it says "Pop!_OS 20.04 is available", I think we should say, "Pop!_OS 20.04 LTS is available".

![LTS Upgrade](https://user-images.githubusercontent.com/13512097/81422793-b62b0b80-9110-11ea-94ad-8d29021d1599.png)
(screenshot from mattermost)

**Comment by ErichRitz** [comment]
On a related note, I'm on 20.04 LTS and pop-upgrade gives me a notification once a day that 20.10 is available.  Obviously I don't want 20.10 because I'm on LTS.  The tool should be smart enough to know that if I'm on the LTS release channel I only want to update to LTS releases.  I've searched but can't find any pop-upgrade specific configuration files.

**Comment by leviport** [comment]
Thanks for the suggestion, but choosing to notify LTS users of non-LTS upgrades was done deliberately. This is what the "Dismiss" button is for -- to suppress notifications for that release.
