### ISSUE TITLE
Upgrading from 19.10 EOL results in ALL apt sources to be removed

### ISSUE THREAD

**Issue by TechnologyMan101** [pop-os/upgrade#118]
After upgrading from 19.10, all of my sources were gone. The ones left were the usual Ubuntu repos and the 2 Pop!_OS repos. The source code for the Pop!_OS repos were gone too. My own sources, like PPAs and other sources were gone.

How it should have looked:
![Screenshot from 2020-08-17 12-24-11](https://user-images.githubusercontent.com/65311278/90535197-7d4afb80-e12f-11ea-8d9a-984d23fe54e4.png)

How it actually looks:
![Screenshot from 2020-08-17 12-19-24](https://user-images.githubusercontent.com/65311278/90535191-7b813800-e12f-11ea-9213-8c594f66a9a6.png)

Note that none of the applications were removed, only the sources.

**Comment by TechnologyMan101** [comment]
The wallpaper and theme were reset too. It was on the old UNLEASH YOUR POTENTIAL wallpaper and on the light theme before the upgrade.

**Comment by jacobgkau** [comment]
I believe third-party repositories being removed by default is intentional. I'd need to double-check whether the process is still supposed to include a prompt for which ones to add back after the upgrade or not. (Third-party repositories were one of the leading causes for failed upgrades and lengthy support calls, that was the rationale for removing them by default-- we can offer much greater assurance of the upgrade process when it only includes the sources we expect.) You should have a .save file in your /etc/apt/sources.list.d that's a copy from before the upgrade, and I see that you already know about Repoman to help add them back.

If the wallpaper was on the default Unleash Your Potential option, then it's correct that it would be changed to the new default option. If you had manually changed the wallpaper away from the Unleash Your Potential option, then it should not have changed during the upgrade since that's no longer a default setting.

**Comment by TechnologyMan101** [comment]
I wonder if upgrading was supposed to change the theme to dark and also removing Pop!_OS source code repos.

**Comment by mmstick** [comment]
If you haven't explicitly changed the default settings, then you will have been switched to the dark theme, because 20.04 changed the default GTK theme to the dark theme.

As for sources, it is intentional to do away with third party PPAs and start with a clean slate with a regenerated sources list. The original source lists are backed up for your reference. Too many issues with PPAs on upgrade.

**Comment by TechnologyMan101** [comment]
Thanks a lot, this clears up everything. I can just rerun my setup script and readd the Pop!_OS source code repos to get all of my sources back, so it's just a minor inconvenience.

**Comment by TechnologyMan101** [comment]
Also just wondering, shouldn't it show the user that it is going to remove sources? It was completely unexpected for me and it did not tell me anything about software sources.
