### ISSUE TITLE
20.10: Decryption screen displays a cryptswap warning after upgrade from 20.04

### ISSUE THREAD

**Issue by leviport** [pop-os/upgrade#123]
After upgrades from 20.04, I'm seeing a warning that states, `cryptsetup: WARNING: cryptswap: couldn't determine device type, assuming default (plain).` The drive still unlocks and the OS boots normally, but the warning may be unsettling for users.

Perhaps this isn't the correct repo for this issue, but I'm not seeing it on fresh Groovy installs, so I figured it could be related to the upgrade process.

![PXL_20201009_222221225](https://user-images.githubusercontent.com/13512097/95636367-318c4280-0a4c-11eb-8033-229dc3667f43.jpg)

**Comment by mmstick** [comment]
I read that add `plain` as an option the crypttab stops this warning. Though this file isn't touched during upgrade, so fresh installs and upgrades should still have the same options defined since the installer configured it. Maybe the cryptsetup package on 20.04 and prior was simply not showing this warning?

**Comment by ids1024** [comment]
> Maybe the cryptsetup package on 20.04 and prior was simply not showing this warning?

Yep, the warning doesn't seem to exist on 20.04. `grep "couldn't" /usr/lib/cryptsetup/functions` shows this line on 20.10, but nothing on 20.04.

> Perhaps this isn't the correct repo for this issue, but I'm not seeing it on fresh Groovy installs, so I figured it could be related to the upgrade process.

If this happens only on upgrades, I wonder what's different. I guess the partition has some additional metadata when created with the newer cryptsetup? Since `/etc/crypttab` seems to be the same in 20.04 and 20.10.

**Comment by ids1024** [comment]
Or, I guess `plain` by definition lacks metadata...

It seems reasonable to set that in  `crypttab`, but I wonder why it seems to happen on upgrades but not new installs.
