### ISSUE TITLE
Upgrades > Disable current extensions

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/upgrade#166]
Dash to Dock is likely to cause problems. Should we disable all extensions for this upgrade?

Are there other upgrade considerations?

**Comment by mmstick** [comment]
The source code for this has already been there

https://github.com/pop-os/upgrade/blob/master/src/gnome_extensions.rs

Either I forgot to add it, or a recent update removed it for some reason

**Comment by mmstick** [comment]
No it's definitely being called on upgrade

**Comment by jacobgkau** [comment]
On `b797d3d`, I've confirmed that Dash to Dock is not disabled when upgrading from 20.10 to 21.04. Both Dash to Dock and Ubuntu Dock are enabled in the extension settings, and only Dash to Dock is visible.

**Comment by isantop** [comment]
We should probably inform users upgrading that their extensions were disabled. That way they know where they can go to try re-enabling any which wouldn't conflict with the new desktop.

**Comment by jackpot51** [comment]
Does disable-user-extensions actually do anything, and how is it reverted by the user?

**Comment by jacobgkau** [comment]
> Does disable-user-extensions actually do anything, and how is it reverted by the user?

I installed Caffeine and ran `gsettings set org.gnome.shell disable-user-extensions true`, and Caffeine was disabled; the on/off switch at the top of the Extensions window was turned off, while the on/off switch next to Caffeine was greyed out:

![extensions](https://user-images.githubusercontent.com/7199422/123281977-5ab00e80-d4c7-11eb-94b2-dd269aef2dff.png)

Switching that top switch back on also turned Caffeine back on, I did not need to re-enable Caffeine individually.

**Comment by jacobgkau** [comment]
> We should check if:
>     1. upgrades actually set that setting
>     2. that setting actually stops additional extensions from loading
>     3. Dash to Dock is not somehow special due to it being loaded in the shell mode

I installed Caffeine and Dash to Dock on 20.10, then upgraded to 21.04. After logging in again, both Caffeine and Dash to Dock were enabled. `gsettings get org.gnome.shell disable-user-extensions` returned `false`, so that setting is not being set (or isn't sticking.) Enabling that setting manually did disable Dash to Dock in addition to Caffeine, so Dash to Dock isn't handled specially with regards to that setting.

**Comment by jackpot51** [comment]
You could try creating a new user, and running the command that the upgrader uses, and see if it sets the setting.

**Comment by jacobgkau** [comment]
I got the `gsettings` command from before from [here](https://github.com/pop-os/upgrade/blob/1a592edc0170d1623b1d2da171d557a9bcd4cf8d/src/gnome_extensions.rs#L24), but I believe the issue is how the upgrader's using `sudo -Hu`. When I try `sudo -Hu system76 gsettings set org.gnome.shell disable-user-extensions true` like the upgrader would run, the gsetting does not change. Just `-H` or `-u system76` also don't work.

That said, I also don't see `disabling gnome-shell extensions for ...` being logged anywhere, so I can't say whether it's actually running anyway. (I see where the disable function is called [here](https://github.com/pop-os/upgrade/blob/1a592edc0170d1623b1d2da171d557a9bcd4cf8d/src/release/mod.rs#L492), but I'm getting neither the info line from the function nor the error line from where it's called.) Based on where the function is being called, I should visibly see extensions being disabled after the upgrade's downloaded but before I reboot to the offline stage, right?

**Comment by jacobgkau** [comment]
Adding `E` to preserve environment variables makes the command work via sudo. So the working command is:

```
sudo -HEu system76 gsettings set org.gnome.shell disable-user-extensions true
```

**Comment by jacobgkau** [comment]
Enabling or disabling individual extensions using `gnome-extensions disable ...` also works with `sudo -HEu` for the current user, but not for other users.

I get messages like this when attempting to run any of these commands for other users:

```
(process:10678): dconf-CRITICAL **: 13:20:28.696: unable to create directory '/run/user/1000/dconf': Permission denied.  dconf will not work properly.
(process:10678): dconf-WARNING **: 13:20:28.696: failed to commit changes to dconf: Could not connect: Permission denied
```

I tried `su - username -c "gsettings set ..."` instead of sudo, but it has the same problem.

**Comment by mmstick** [comment]
I remember this working when I implemented it. Maybe those dconf errors are related.

**Comment by mmstick** [comment]
Sometimes I wish dconf was text files, rather than a registry. Or at least had a library for interacting with that registry directly.

**Comment by jacobgkau** [comment]
It would be a little intrusive, but simply moving each user's extensions into some other directory (or removing them altogether) might be easier. From one user, I can use sudo to perform the following:
```
mkdir /home/username/.local/share/gnome-shell/extensions.bak
mv /home/username/.local/share/gnome-shell/extensions/* /home/username/.local/share/gnome-shell/extensions.bak
```
And upon the original user logging in, the extensions are obviously not loaded anymore. This would require the user to individually reinstall any extensions they want to re-enable.

**Comment by mmstick** [comment]
If we can't disable extensions this way anymore, that will have to be our choice. I liked having them disabled this way because it lets them go to extensions.gnome..org and update them before re-enabling them.
