### ISSUE TITLE
Complete fstab and libc6 fixes

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/upgrade#218]

**Comment by mmstick** [comment]
I believe this was already fixed a while back.

**Comment by jacobgkau** [comment]
Yes, fstab was fixed by https://github.com/pop-os/upgrade/pull/170.

I'm not sure exactly which libc6 fix is being referred to here. We never found a way to recreate https://github.com/pop-os/upgrade/issues/160 -- was that one that we thought was related to not purging PPAs?

https://github.com/pop-os/upgrade/pull/162 / https://github.com/pop-os/upgrade/pull/142 included a libc6:i386 fix.
