### ISSUE TITLE
Pop_OS not upgrading to version 21.10 from 21.10

### ISSUE THREAD

**Issue by Kunal-Attri** [pop-os/upgrade#230]
Kindly see the screenshot attached for reference, and correct the error ASAP

![Screenshot from 2021-12-14 22-48-34](https://user-images.githubusercontent.com/35298757/146047680-5dbb4c1b-52c1-421c-b209-e0b17dca7522.png)

**Comment by jacobgkau** [comment]
The new pop-upgrade release is currently building on Launchpad. pop-upgrade and apt will see the update available when it's done building and released there.

**Comment by Kunal-Attri** [comment]
> The new pop-upgrade release is currently building on Launchpad. pop-upgrade and apt will see the update available when it's done building and released there.

Okay

**Comment by jacobgkau** [comment]
The status of the Launchpad builds is publicly available, if you'd like to watch them: https://launchpad.net/~system76/+archive/ubuntu/proposed/+packages?field.name_filter=pop-upgrade&field.status_filter=published&field.series_filter= 

In the "Build Status" column, all of the clocks need to turn into green checkmarks. (Future releases won't need to wait for this, since Pop!_OS 21.10 no longer uses Launchpad for the Pop!_OS repository.)

**Comment by Kunal-Attri** [comment]
It upgrading now
