### ISSUE TITLE
Designs for OS Upgrade and Refresh.

### ISSUE THREAD

**Issue by maria-komarova** [pop-os/upgrade#69]
Below are the most recent designs of the OS Upgrade & Refresh page. See the previous discussion here: [https://github.com/pop-os/upgrade/pull/67]

**1.** The default when everything is up to date is the same.
![Default](https://user-images.githubusercontent.com/57502897/70063040-64e88000-15a4-11ea-91dd-559017791f22.png)
![Default-Refresh](https://user-images.githubusercontent.com/57502897/70063049-674ada00-15a4-11ea-8c59-99fc2b02d5cf.png)

If w can find the same icon as used in the OS Upgrade popup that would be great. 

**2.** When a user upgraded to 19.10 but needs updating the recovery partition, the design as follows. We will require a user to update the Recovery Partition in order to use Refresh OS regardless of the presence or absence of the Refresh OS option in the recovery partition. When the user updates the Recovery Partition, show the same view as default. 
![19 10noRefresh-Update-Refresh](https://user-images.githubusercontent.com/57502897/70063162-8e091080-15a4-11ea-96f3-6fe219340c32.png)
![19 10noRefresh-downloading](https://user-images.githubusercontent.com/57502897/70063171-91040100-15a4-11ea-8588-6f55236175ae.png)
![19 10noRefresh-updating](https://user-images.githubusercontent.com/57502897/70063180-93665b00-15a4-11ea-8fd5-f269ae0b2994.png)

**3.** When the system is before 19.10 we will show the Upgrade available in addition to the previous case.
![OldOS-Update-to-Refresh](https://user-images.githubusercontent.com/57502897/70063255-af69fc80-15a4-11ea-9762-2f48a909e42d.png)
![OldOS-downloadingRP](https://user-images.githubusercontent.com/57502897/70063260-b42eb080-15a4-11ea-8354-4424c8481315.png)
![OldOS-Upgrade-Refresh](https://user-images.githubusercontent.com/57502897/70063262-b5f87400-15a4-11ea-9a20-c09c1b0a1be8.png)
![OldOS-Upgrade-Refreshing](https://user-images.githubusercontent.com/57502897/70063271-b7c23780-15a4-11ea-8553-2b8130ff5818.png)

**4.** LTS users will see pretty much the same with the option to dismiss notifications for the upgrade. 
![LTS-notifications](https://user-images.githubusercontent.com/57502897/70063285-c01a7280-15a4-11ea-8e91-a77a97fba670.png)
![LTS-dismissedNotif](https://user-images.githubusercontent.com/57502897/70063295-c27ccc80-15a4-11ea-8630-1fdc6e25492c.png)

When the update for the Recovery Partition is available show users the usual notification about the update and direct them to this page in the Settings once they click on the notification.

**Comment by brs17** [comment]
I have a few comments regarding the latest mockups.

- With the Recovery partition update under Refresh OS, when an update is available, I read the phrase Refresh OS twice before even getting to what the affirmative Update button actually does. Is it potentially unclear that selecting this button will not start a refresh os install? 
- When a recovery partition update is available, there is no description of what the Refresh OS is at all. Potentially this keeps users from selecting any option here.
- While updating the recovery partition makes sense from the interest of doing a refresh os install, the Recovery Partition update is not really related or similar to a Refresh OS Install. I think the OS Upgrade and Recovery Partition Update are far more similar than Recovery partition update and Refresh OS are.

- When a recovery partition update is available, I believe it should be made clear that this is not just for Refreshing the OS but should be encouraged with similar weight as an OS Upgrade. 

- In addition, the current mockups show the `Pop!_OS 19.10 is available`  row when an update is available, but then the entire `OS Upgrade` subtitle disappears when it is up to date. If we are ok with that, why not just put the Recovery partition update in a row of its own? Perhaps when both the OS and Recovery partition are up to date, the description under Operating System could detail running the most current OS as well as an up to date recovery partition?

**Comment by brs17** [comment]
- Are we ok with the Refresh OS button being neutral and not destructive?
- Currently for the Recovery Partition update, the download description says "Download X GB", might this be too much of an action item when this text is not actually selectable? Perhaps something like "Download Size: X GB"?
- Will there be a notification for Recovery Partition updates? What is the copy for that?

**Comment by WatchMkr** [comment]
> With the Recovery partition update under Refresh OS, when an update is available, I read the phrase Refresh OS twice before even getting to what the affirmative Update button actually does. Is it potentially unclear that selecting this button will not start a refresh os install?

Let's change the copy to "An update to the recovery partition is required for Refresh OS"

> When a recovery partition update is available, there is no description of what the Refresh OS is at all. Potentially this keeps users from selecting any option here.

Good catch. I don't think the download X GB is necessary or adds much value. We don't do it with OS Upgrades and haven't had any complaints that I'm aware of. Let's use that space to describe the feature "Refresh OS reinstalls Pop!_OS while retaining your users and files."

> While updating the recovery partition makes sense from the interest of doing a refresh os install, the Recovery Partition update is not really related or similar to a Refresh OS Install. I think the OS Upgrade and Recovery Partition Update are far more similar than Recovery partition update and Refresh OS are.

The recovery partition is for two things. 1) Refresh OS and 2) Fixing problems in the currently installed OS. From a user perspective, the recovery partition is associated with Refresh OS rather than OS Upgrade.

> In addition, the current mockups show the Pop!_OS 19.10 is available row when an update is available, but then the entire OS Upgrade subtitle disappears when it is up to date. If we are ok with that, why not just put the Recovery partition update in a row of its own? Perhaps when both the OS and Recovery partition are up to date, the description under Operating System could detail running the most current OS as well as an up to date recovery partition?

OS Upgrade disappearing is an error in the design. The design will be updated.

> Are we ok with the Refresh OS button being neutral and not destructive?

Yes

> Currently for the Recovery Partition update, the download description says "Download X GB", might this be too much of an action item when this text is not actually selectable? Perhaps something like "Download Size: X GB"?

Being removed

> Will there be a notification for Recovery Partition updates? What is the copy for that?

Yes. @maria-komarova please draft copy that has the same style as the OS Upgrade notification

**Comment by mmstick** [comment]
There may be times when you'd want to visit the recovery partition without having to download a 2-3GB update to do it. There may also be an issue with the installed OS that is causing it to be unable to successfully download and apply the update.

How will we handle the need to upgrade the recovery partition before or after an OS upgrade?

**Comment by isantop** [comment]
Would it be possible to automatically download and update the recovery partition during the OS upgrade? It might make sense to upgrade the recovery partition first, so that in the event that the upgrade doesn't work, the user can perform a refresh or reinstall from the new version directly instead of recovering to the previous version and then needing to upgrade again.

**Comment by mmstick** [comment]
It's very much possible to either update the recovery partition before or during the upgrade. This is what the code was originally doing before the upgrade daemon was released. The Pop API service already reports the size of ISOs in bytes, so it's not much effort to add that. Technically we could also do the same for performing a release upgrade, since the apt command can report remaining download size for a dry run.

**Comment by maria-komarova** [comment]
I would imagine that if we tie the Recovery Partition Update to the Refresh OS, we will need to update the Recovery Partition as part of the OS Upgrade starting with the next release. I think it makes sense to start with the Recovery Partition update first and then download the OS upgrade.

**Comment by maria-komarova** [comment]
An update to the designs:

**1.** The default when everything is up to date:
![Default](https://user-images.githubusercontent.com/57502897/70070782-65d3de80-15b1-11ea-98cc-f4caddbce9bd.png)
![Default-Refresh](https://user-images.githubusercontent.com/57502897/70070787-679da200-15b1-11ea-91c8-513a39b199e9.png)

If we can find the same icon as used in the OS Upgrade popup that would be great. 

**2.** When a user upgraded to 19.10 but needs updating the recovery partition, the design as follows. We will require a user to update the Recovery Partition in order to use Refresh OS regardless of the presence or absence of the Refresh OS option in the recovery partition. When the user updates the Recovery Partition, show the same view as default. 
![19 10noRefresh-Update-Refresh](https://user-images.githubusercontent.com/57502897/70070834-7b490880-15b1-11ea-9804-899ae80b4385.png)
![19 10noRefresh-downloading](https://user-images.githubusercontent.com/57502897/70071619-da5b4d00-15b2-11ea-95e4-b45525d3e666.png)
![19 10noRefresh-updating](https://user-images.githubusercontent.com/57502897/70071640-e21af180-15b2-11ea-8fcb-ddf97022dec7.png)




**3.** When the system is before 19.10 we will show the Upgrade available in addition to the previous case.
![OldOS-Update-to-Refresh](https://user-images.githubusercontent.com/57502897/70070887-9ae03100-15b1-11ea-8a33-272b4d6c586e.png)
![OldOS-downloadingRP](https://user-images.githubusercontent.com/57502897/70071679-efd07700-15b2-11ea-8163-04c511c88c0a.png)
![OldOS-Refresh1](https://user-images.githubusercontent.com/57502897/70071008-d2e77400-15b1-11ea-9903-3e39c83eb80a.png)
![OldOS-Refresh2](https://user-images.githubusercontent.com/57502897/70071020-d844be80-15b1-11ea-9b04-978fe6e407af.png)


**4.** LTS users will see pretty much the same with the option to dismiss notifications for the upgrade. 
![LTS-notifications](https://user-images.githubusercontent.com/57502897/70072010-6cfbec00-15b3-11ea-8509-ea97cf7e8a4d.png)
![LTS-dismissedNotif](https://user-images.githubusercontent.com/57502897/70072022-6ff6dc80-15b3-11ea-8041-613af60031cc.png)



When the update for the Recovery Partition is available show users the usual notification about the update and direct them to this page in the Settings once they click on the notification. Below is the draft of the notification.
![SystemSoftwareInstall](https://user-images.githubusercontent.com/57502897/70071048-eb578e80-15b1-11ea-8510-779942dd6768.png)

Once the system downloaded and installed Recovery Partition Update, we might show the notification with the copy "The Recovery Partition update was successfully installed. The system is ready to Refresh OS."

**Comment by mmstick** [comment]
@maria-komarova We can certainly use the same icon. If you ever want to find out which icon is in a GTK application, if you open the application from the terminal with `env GTK_DEBUG=interactive NAME_OF_APPLICATION`, a second GTK inspector window will appear, which allows you to click on an image in the application it's connected to, and it will tell you the name of the icon, as well as the margins and padding (including allowing you to change these to see how certain changes would look in practice) in the properties.

The refresh dialog seems a bit empty. Would it be a good idea if we were to add some extra details in there about the refresh process, as well as remind the user that they should save and close everything before the process begins?

**Comment by maria-komarova** [comment]
@mmstick Yes, that sounds like a great idea! Do we have an example of where it was done before? 
And thanks for the advice about figuring out the name of the icon and padding, very helpful.

**Comment by mmstick** [comment]
At least for OS upgrades, the dialog does make a mention about making sure to plug into power when on battery, as well as displaying a changelog for all the changes happened since the release that they were on. We don't have a changelog to provide for recovery partition updates, but perhaps we could describe what's going to happen with a bit more detail. Something like

* All system-wide changes will be lost, with the exception of:
    * The timezone
    * The system locale (language)
    * The keyboard layout
* All files outside of the /home directory will be lost
* User accounts in the /home directory will be retained
* User files and settings will therefore remain the same

**Comment by leviport** [comment]
>I don't think the download X GB is necessary or adds much value. We don't do it with OS Upgrades and haven't had any complaints that I'm aware of. Let's use that space to describe the feature "Refresh OS reinstalls Pop!_OS while retaining your users and files."

I have seen a complaint about the download size from a friend of mine that bought a gaze14. He's a contractor working in a remote location with slow, metered internet. I warned him about the download size for the 19.10 upgrade so it wasn't entirely unexpected for him, but the download did take him about a day and a half, and he did have to pay for the data used.

Obviously this is a bit of an edge case, but metered connections are not terribly uncommon, especially for people using mobile hotspots. When the download could potentially cost people money, I think a heads-up would be appreciated.

**Comment by mmstick** [comment]
Regarding bandwidth concerns, I have wondered how we could enable offline upgrades of the recovery partition. Technically anyone with a copy of the ISO can use that ISO to upgrade the recovery partition. That way if you have a network with 100s of Pop!_OS installations, you don't have to download the ISO 100s of times to update each system on the network.

**Comment by mmstick** [comment]
Thinking about that, if I were to allow a system to configure a specific path for caching the ISO, then they could mount that path to a network share in order to eliminate the need to fetch a new ISO every time. No UX changes would be needed.

**Comment by maria-komarova** [comment]
Here is the chart for what we show and when. Basically, if you are offline but you have a Refresh OS option in the recovery partition we should show the Refresh OS option in the settings. I don't know if that answers your concern. 
![FlowChart](https://user-images.githubusercontent.com/57502897/70077057-4cd12a80-15bd-11ea-9f67-1668c55b21ca.png)

**Comment by maria-komarova** [comment]
Updated designs after some discussions in person. The idea is to create a section for **OS Recovery**. The section includes both **recovery partition updates and Refresh OS**. In addition, this section includes a new feature - **Factory Reset**. 
**New page title - "OS Upgrade & Recovery".**
Below is the chart that explains how recovery partition updates and Refresh OS should load on the page. Factory Reset should always be present for those who have a recovery partition. 
![FlowChart](https://user-images.githubusercontent.com/57502897/70093038-caf0f980-15dc-11ea-8c9d-28ce4caff196.png)

When the recovery partition update is available show the following notification:
![SystemSoftwareInstall](https://user-images.githubusercontent.com/57502897/70093055-d6442500-15dc-11ea-9365-f895113980a9.png)

**1. Everything up to date:**
![Default](https://user-images.githubusercontent.com/57502897/70097576-f0830080-15e6-11ea-9633-636cf86ba1ca.png)
![Default-Refresh](https://user-images.githubusercontent.com/57502897/70097580-f24cc400-15e6-11ea-9d64-162a20c5140e.png)

**2.** This is step by step if a user has Pop!_OS 19.10 **with the Refresh OS option** in the recovery partition. Mostly to show download for the recovery partition update. Once it is updated the screen as in the previous case.
![RefreshOption-1](https://user-images.githubusercontent.com/57502897/70097590-f7aa0e80-15e6-11ea-8014-9c61f2e04513.png)
![RefreshOption-2](https://user-images.githubusercontent.com/57502897/70097593-f8db3b80-15e6-11ea-9824-d30dce2a76c1.png)
![RefreshOption-3](https://user-images.githubusercontent.com/57502897/70097596-faa4ff00-15e6-11ea-90e5-3848ae37c158.png)

**3. If there is no Refresh OS option in the recovery partition**, this is how the process would look like.
![OldOS-Update-to-Refresh](https://user-images.githubusercontent.com/57502897/70097619-05f82a80-15e7-11ea-8b36-edbd5cdcf428.png)
![OldOS-downloadingRP](https://user-images.githubusercontent.com/57502897/70097629-0c86a200-15e7-11ea-95fb-d923f7cbd7f4.png)
![OldOS-downloadingRP-1](https://user-images.githubusercontent.com/57502897/70097636-0ee8fc00-15e7-11ea-8dd3-d7ff1c013a64.png)
![OldOS-Upgrade-Refresh](https://user-images.githubusercontent.com/57502897/70097650-15777380-15e7-11ea-917f-67b53aa9a83b.png)
![OldOS-Upgrade-Refreshing](https://user-images.githubusercontent.com/57502897/70097662-1b6d5480-15e7-11ea-83a8-1eb49f5bfc2a.png)

**4. For LTS-users** include the ability to dismiss notifications for the OS Upgrade. 
![LTS-notifications](https://user-images.githubusercontent.com/57502897/70097673-20ca9f00-15e7-11ea-98f6-fbec56c6918a.png)
![LTS-dismissedNotif](https://user-images.githubusercontent.com/57502897/70097676-22946280-15e7-11ea-8821-cedaa9650d50.png)


**5. For the Factory Reset:**
![Default-FactoryReset](https://user-images.githubusercontent.com/57502897/70097550-e95bf280-15e6-11ea-9b5b-847804df68db.png)

**Comment by mmstick** [comment]
@maria-komarova It looks :ok_hand: to me. I'm already working on it right now.

**Comment by WatchMkr** [comment]
@maria-komarova Looks great!

**Comment by leviport** [comment]
I had a few thoughts since our meeting that I wanted to share. 

- Factory reset might not be the right term for a simple OS reinstall. For example, selecting factory reset in other OSes presents an option to securely wipe all stored data, intended for users who are planning on selling or giving away the machine. A reinstall does not do this by default. 
-- A secure wipe is usually accomplished by filling the drive with zeroes or random data before re-partitioning it, and therefore takes a fair bit of time. This is why other OSes only present it as an option, because a simple reinstall shouldn't take that huge amount of time by default.
-- If we go with the option to securely wipe all data, we probably also have to think about what happens to other partitions and secondary hard drives, and how those warnings are presented to the user.

- The flowchart seems a little bit out of order and incomplete. 
-- I believe the "Does the user have an internet connection?" box should be prior to the "Is there a Refresh OS option in the recovery partition?" box, since internet connection conditional is presented in the "no" branch. 
-- It might be good to add another blue box below the existing ones that deals with whether or not there is an update available for the recovery partition. For example, the flowchart doesn't exactly specify whether or not Refresh will be enabled if the recovery partition is not fully up-to-date, but still has the Refresh option available.

- The fact that some buttons (OS update and recovery partition update) lead directly to actions, and others (Refresh & Factory Reset) instead spawn dialogs seems a little strange. I'm not sure I have an indication that clicking the red "Reset" button will give me more information about factory reset before wiping out everything on my hard drive. There was talk about implementing drop-downs similar to those found in the firmware updater; maybe those dropdowns would be useful in this situation? 
![Screenshot from 2019-12-04 11-25-12](https://user-images.githubusercontent.com/13512097/70169815-ca15a180-1688-11ea-9e1a-b2bb096ef5b9.png)

**Comment by maria-komarova** [comment]
Update - take out the Factory Reset feature for now. We will think about it more. Keep Recovery Partition updates and Refresh OS in the OS Recovery section. The designs stay the same with the exception of the Factory Reset not being there. 
Can I update the wiki?
